/**
 * Comprehensive PDF Report Generation
 * Supports client-side PDF generation and Prokerala API integration
 * Inspired by AstroSage and AstroTalk patterns
 */

import type { KundliResult, DoshaAnalysis, KundliChart } from "@/types/astrology";
import type {
  PersonalityAnalysis,
  CareerAnalysis,
  HealthAnalysis,
  FinanceAnalysis,
  RelationshipAnalysis,
  EducationAnalysis,
  LuckyElements,
  YearlyPrediction,
} from "./lifeReportAnalysis";

type PDFReportData = {
  kundli: KundliResult & { dosha?: DoshaAnalysis; chart?: KundliChart };
  userName: string;
  generatedAt: string;
  personality?: PersonalityAnalysis;
  career?: CareerAnalysis;
  health?: HealthAnalysis;
  finance?: FinanceAnalysis;
  relationships?: RelationshipAnalysis;
  education?: EducationAnalysis;
  luckyElements?: LuckyElements;
  yearlyPrediction?: YearlyPrediction;
};

type PDFOptions = {
  format?: "basic" | "detailed" | "premium";
  includeChart?: boolean;
  includeAnalysis?: boolean;
  language?: "en" | "hi";
  branding?: {
    name?: string;
    footer?: string;
  };
};

/**
 * Check if Prokerala API is configured for PDF generation
 */
export async function canUseProkeralaPDF(): Promise<boolean> {
  try {
    const response = await fetch("/api/astrology/status");
    const data = await response.json();
    return data?.configured === true;
  } catch {
    return false;
  }
}

/**
 * Generate PDF using Prokerala API
 */
export async function generatePDFViaProkerala(
  reportData: PDFReportData,
  options: PDFOptions = {}
): Promise<Blob | null> {
  try {
    const kundli = reportData.kundli;
    
    // Parse birth details from Kundli
    const [year, month, day] = kundli.summary[0]?.match(/\d{4}/)?.[0]?.split("") || [];
    // We need actual birth details - this is a placeholder
    // In production, store birth details separately
    
    const response = await fetch("/api/reports/pdf/prokerala", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        type: options.format || "detailed",
        data: reportData,
        options: {
          report: {
            brand_name: options.branding?.name || "AstroSetu",
            name: `${options.format === "premium" ? "Premium" : options.format === "detailed" ? "Detailed" : "Basic"} Life Report`,
            caption: "Generated by AstroSetu",
            la: options.language || "en",
          },
          template: {
            footer: options.branding?.footer || "AstroSetu - Bridging humans with cosmic guidance",
            style: "vedic-astro-green",
          },
          modules: [
            {
              name: "personal-reading",
              options: {
                chart_style: "south-indian",
                include_dosha: true,
                include_dasha: true,
              },
            },
          ],
        },
      }),
    });

    if (!response.ok) {
      throw new Error("Prokerala PDF generation failed");
    }

    const blob = await response.blob();
    return blob;
  } catch (error) {
    console.warn("[PDF] Prokerala PDF generation failed, falling back to client-side:", error);
    return null;
  }
}

/**
 * Generate PDF client-side using jsPDF
 */
export async function generatePDFClientSide(
  reportData: PDFReportData,
  options: PDFOptions = {}
): Promise<Blob> {
  // Dynamic import of jsPDF to avoid SSR issues
  const { jsPDF } = await import("jspdf");
  
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;
  const contentWidth = pageWidth - 2 * margin;
  let yPos = margin;

  // Helper function to add new page if needed
  const checkNewPage = (requiredHeight: number) => {
    if (yPos + requiredHeight > pageHeight - margin) {
      doc.addPage();
      yPos = margin;
      return true;
    }
    return false;
  };

  // Helper function to add text with wrapping
  const addWrappedText = (text: string, fontSize: number, color: number[] = [0, 0, 0], maxWidth?: number) => {
    doc.setFontSize(fontSize);
    doc.setTextColor(color[0], color[1], color[2]);
    const lines = doc.splitTextToSize(text, maxWidth || contentWidth);
    lines.forEach((line: string) => {
      checkNewPage(6);
      doc.text(line, margin, yPos);
      yPos += 6;
    });
    return lines.length * 6;
  };

  // Helper function to add section header
  const addSectionHeader = (title: string, icon: string = "") => {
    checkNewPage(15);
    yPos += 5;
    doc.setFontSize(16);
    doc.setTextColor(139, 92, 246); // Purple
    doc.setFont("helvetica", "bold");
    const headerText = icon ? `${icon} ${title}` : title;
    doc.text(headerText, margin, yPos);
    yPos += 8;
    
    // Add separator line
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, yPos, pageWidth - margin, yPos);
    yPos += 5;
  };

  // Cover Page
  doc.setFillColor(255, 248, 220); // Saffron background
  doc.rect(0, 0, pageWidth, pageHeight, "F");
  
  doc.setTextColor(30, 41, 59); // Slate
  doc.setFontSize(32);
  doc.setFont("helvetica", "bold");
  doc.text("🔮", pageWidth / 2, pageHeight / 2 - 40, { align: "center" });
  
  doc.setFontSize(24);
  doc.text("Life Report", pageWidth / 2, pageHeight / 2 - 20, { align: "center" });
  
  doc.setFontSize(16);
  doc.setFont("helvetica", "normal");
  doc.text("Complete Vedic Astrology Analysis", pageWidth / 2, pageHeight / 2 - 5, { align: "center" });
  
  doc.setFontSize(14);
  doc.text(reportData.userName, pageWidth / 2, pageHeight / 2 + 15, { align: "center" });
  
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  const generatedDate = new Date(reportData.generatedAt).toLocaleDateString("en-IN", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  doc.text(`Generated on ${generatedDate}`, pageWidth / 2, pageHeight / 2 + 25, { align: "center" });
  
  doc.setFontSize(9);
  doc.text("AstroSetu - Bridging humans with cosmic guidance", pageWidth / 2, pageHeight - 20, { align: "center" });
  
  // New page for content
  doc.addPage();

  // Table of Contents
  if (options.format !== "basic") {
    addSectionHeader("Table of Contents");
    const toc = [
      "1. Executive Summary",
      "2. Birth Chart & Planetary Positions",
      "3. Personality Analysis",
      "4. Career & Profession",
      "5. Relationships & Marriage",
      "6. Finance & Wealth",
      "7. Health & Wellbeing",
      "8. Education & Learning",
      "9. Dosha Analysis & Remedies",
      "10. Lucky Elements",
      "11. Yearly Predictions",
    ];
    
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    doc.setFont("helvetica", "normal");
    toc.forEach((item) => {
      checkNewPage(7);
      doc.text(item, margin + 5, yPos);
      yPos += 7;
    });
    yPos += 10;
  }

  // Executive Summary
  addSectionHeader("Executive Summary", "📋");
  const kundli = reportData.kundli;
  
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Personal Details", margin, yPos);
  yPos += 7;
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  const personalDetails = [
    `Name: ${reportData.userName}`,
    `Ascendant (Lagna): ${kundli.ascendant}`,
    `Rashi (Moon Sign): ${kundli.rashi}`,
    `Nakshatra: ${kundli.nakshatra}`,
    `Tithi: ${kundli.tithi}`,
  ];
  
  personalDetails.forEach((detail) => {
    checkNewPage(6);
    doc.text(detail, margin + 5, yPos);
    yPos += 6;
  });
  yPos += 5;

  // Key Highlights
  if (kundli.summary && kundli.summary.length > 0) {
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text("Key Highlights", margin, yPos);
    yPos += 7;
    
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    kundli.summary.slice(0, 5).forEach((highlight, idx) => {
      checkNewPage(6);
      doc.text(`${idx + 1}. ${highlight}`, margin + 5, yPos);
      yPos += 6;
    });
    yPos += 10;
  }

  // Planetary Positions Table
  addSectionHeader("Planetary Positions", "🪐");
  
  // Table header
  const tableHeaders = ["Planet", "Sign", "Degree", "House", "Status"];
  const colWidths = [35, 35, 25, 25, 30];
  let xPos = margin;
  
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setFillColor(250, 204, 21); // Amber
  tableHeaders.forEach((header, idx) => {
    doc.rect(xPos, yPos - 5, colWidths[idx], 7, "F");
    doc.setTextColor(0, 0, 0);
    doc.text(header, xPos + 2, yPos);
    xPos += colWidths[idx];
  });
  yPos += 8;

  // Table rows
  doc.setFont("helvetica", "normal");
  kundli.planets.forEach((planet) => {
    checkNewPage(7);
    xPos = margin;
    const rowData = [
      planet.name,
      planet.sign,
      `${planet.degree}°`,
      `H${planet.house}`,
      planet.retrograde ? "Retrograde" : "Direct",
    ];
    
    rowData.forEach((cell, idx) => {
      doc.text(cell, xPos + 2, yPos);
      xPos += colWidths[idx];
    });
    yPos += 7;
    
    // Add separator line
    doc.setDrawColor(220, 220, 220);
    doc.line(margin, yPos - 1, pageWidth - margin, yPos - 1);
  });
  yPos += 10;

  // Personality Analysis
  if (reportData.personality && options.format !== "basic") {
    addSectionHeader("Personality Analysis", "👤");
    
    if (reportData.personality.strengths.length > 0) {
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.text("Strengths", margin, yPos);
      yPos += 7;
      
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      reportData.personality.strengths.forEach((strength) => {
        checkNewPage(6);
        doc.text(`• ${strength}`, margin + 5, yPos);
        yPos += 6;
      });
      yPos += 5;
    }

    if (reportData.personality.weaknesses.length > 0) {
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.text("Areas for Improvement", margin, yPos);
      yPos += 7;
      
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      reportData.personality.weaknesses.slice(0, 5).forEach((weakness) => {
        checkNewPage(6);
        doc.text(`• ${weakness}`, margin + 5, yPos);
        yPos += 6;
      });
      yPos += 10;
    }
  }

  // Career Analysis
  if (reportData.career && options.format !== "basic") {
    addSectionHeader("Career & Profession", "💼");
    
    addWrappedText(reportData.career.overview, 10, [0, 0, 0], contentWidth);
    yPos += 5;
    
    if (reportData.career.suitableProfessions.length > 0) {
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.text("Suitable Professions", margin, yPos);
      yPos += 7;
      
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      reportData.career.suitableProfessions.slice(0, 6).forEach((prof) => {
        checkNewPage(6);
        doc.text(`• ${prof}`, margin + 5, yPos);
        yPos += 6;
      });
      yPos += 10;
    }
  }

  // Relationships Analysis
  if (reportData.relationships && options.format !== "basic") {
    addSectionHeader("Relationships & Marriage", "💑");
    
    addWrappedText(reportData.relationships.overview, 10, [0, 0, 0], contentWidth);
    yPos += 5;
    
    if (reportData.relationships.marriageTiming) {
      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      doc.text("Marriage Timing:", margin, yPos);
      yPos += 6;
      doc.setFont("helvetica", "normal");
      addWrappedText(reportData.relationships.marriageTiming, 10, [0, 0, 0], contentWidth);
      yPos += 5;
    }
    yPos += 5;
  }

  // Finance Analysis
  if (reportData.finance && options.format !== "basic") {
    addSectionHeader("Finance & Wealth", "💰");
    
    addWrappedText(reportData.finance.overview, 10, [0, 0, 0], contentWidth);
    yPos += 5;
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text(`Earning Potential: ${reportData.finance.earningPotential}`, margin, yPos);
    yPos += 7;
    
    if (reportData.finance.investmentAdvice.length > 0) {
      doc.setFont("helvetica", "normal");
      reportData.finance.investmentAdvice.slice(0, 4).forEach((advice) => {
        checkNewPage(6);
        doc.text(`• ${advice}`, margin + 5, yPos);
        yPos += 6;
      });
    }
    yPos += 5;
  }

  // Health Analysis
  if (reportData.health && options.format !== "basic") {
    addSectionHeader("Health & Wellbeing", "🏥");
    
    addWrappedText(reportData.health.overview, 10, [0, 0, 0], contentWidth);
    yPos += 5;
    
    if (reportData.health.healthTips.length > 0) {
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      reportData.health.healthTips.slice(0, 5).forEach((tip) => {
        checkNewPage(6);
        doc.text(`• ${tip}`, margin + 5, yPos);
        yPos += 6;
      });
    }
    yPos += 5;
  }

  // Dosha Analysis
  if (kundli.dosha) {
    addSectionHeader("Dosha Analysis & Remedies", "💎");
    
    const dosha = kundli.dosha;
    
    // Manglik Dosha
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text("Manglik Dosha:", margin, yPos);
    yPos += 7;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(`Status: ${dosha.manglik?.status} (${dosha.manglik?.severity} Severity)`, margin + 5, yPos);
    yPos += 6;
    
    if (dosha.manglik?.remedies && dosha.manglik.remedies.length > 0) {
      doc.text("Remedies:", margin + 5, yPos);
      yPos += 6;
      dosha.manglik.remedies.slice(0, 3).forEach((remedy) => {
        checkNewPage(6);
        doc.text(`• ${remedy}`, margin + 10, yPos);
        yPos += 6;
      });
    }
    yPos += 5;

    // Kaal Sarp Dosha
    doc.setFont("helvetica", "bold");
    doc.text("Kaal Sarp Dosha:", margin, yPos);
    yPos += 7;
    doc.setFont("helvetica", "normal");
    doc.text(
      `Status: ${dosha.kaalSarp?.present ? `Present (${dosha.kaalSarp.type || "Unknown"})` : "Not Present"}`,
      margin + 5,
      yPos
    );
    yPos += 10;
  }

  // Lucky Elements
  if (reportData.luckyElements && options.format !== "basic") {
    addSectionHeader("Lucky Elements", "🍀");
    
    const elements = reportData.luckyElements;
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("Lucky Colors:", margin, yPos);
    yPos += 6;
    doc.setFont("helvetica", "normal");
    doc.text(elements.colors.join(", "), margin + 5, yPos);
    yPos += 7;
    
    doc.setFont("helvetica", "bold");
    doc.text("Lucky Numbers:", margin, yPos);
    yPos += 6;
    doc.setFont("helvetica", "normal");
    doc.text(elements.numbers.join(", "), margin + 5, yPos);
    yPos += 7;
    
    doc.setFont("helvetica", "bold");
    doc.text("Favorable Days:", margin, yPos);
    yPos += 6;
    doc.setFont("helvetica", "normal");
    doc.text(elements.days.join(", "), margin + 5, yPos);
    yPos += 10;
  }

  // Yearly Prediction
  if (reportData.yearlyPrediction && options.format === "premium") {
    addSectionHeader(`Yearly Prediction ${reportData.yearlyPrediction.year}`, "📅");
    
    addWrappedText(reportData.yearlyPrediction.overview, 10, [0, 0, 0], contentWidth);
    yPos += 10;
    
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text("Area-wise Predictions:", margin, yPos);
    yPos += 7;
    
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(`Career: ${reportData.yearlyPrediction.career}`, margin + 5, yPos);
    yPos += 6;
    checkNewPage(6);
    doc.text(`Health: ${reportData.yearlyPrediction.health}`, margin + 5, yPos);
    yPos += 6;
    checkNewPage(6);
    doc.text(`Finance: ${reportData.yearlyPrediction.finance}`, margin + 5, yPos);
    yPos += 10;
  }

  // Footer on last page
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Page ${i} of ${totalPages}`,
      pageWidth - margin - 20,
      pageHeight - 10
    );
    doc.text(
      options.branding?.footer || "AstroSetu - Bridging humans with cosmic guidance",
      margin,
      pageHeight - 10
    );
  }

  // Generate blob
  const pdfBlob = doc.output("blob");
  return pdfBlob;
}

/**
 * Main PDF generation function
 * Tries Prokerala API first, falls back to client-side generation
 */
export async function generatePDF(
  reportData: PDFReportData,
  options: PDFOptions = {}
): Promise<Blob> {
  // Try Prokerala API first if available
  if (options.format !== "basic") {
    const prokeralaBlob = await generatePDFViaProkerala(reportData, options);
    if (prokeralaBlob) {
      return prokeralaBlob;
    }
  }

  // Fall back to client-side generation
  return generatePDFClientSide(reportData, options);
}

/**
 * Download PDF with filename
 */
export async function downloadPDF(
  reportData: PDFReportData,
  options: PDFOptions = {},
  filename?: string
): Promise<void> {
  const blob = await generatePDF(reportData, options);
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename || `LifeReport_${reportData.userName}_${new Date().toISOString().split("T")[0]}.pdf`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

