import { NextResponse } from "next/server";
import { checkRateLimit, handleApiError, parseJsonBody, validateRequestSize } from "@/lib/apiHelpers";
import { prokeralaRequest } from "@/lib/astrologyAPI";

/**
 * Generate PDF report using Prokerala API
 * POST /api/reports/pdf/prokerala
 */
export async function POST(req: Request) {
  try {
    // Rate limiting
    const rateLimitResponse = checkRateLimit(req, '/api/reports/pdf/prokerala');
    if (rateLimitResponse) return rateLimitResponse;
    
    // Validate request size
    validateRequestSize(req.headers.get('content-length'), 500 * 1024); // 500KB max
    
    const json = await parseJsonBody<Record<string, any>>(req);
    const { data, options } = json;

    if (!data || !data.kundli) {
      return NextResponse.json(
        { ok: false, error: "Invalid report data" },
        { status: 400 }
      );
    }

    const kundli = data.kundli;
    
    // Extract birth details - we need actual datetime and coordinates
    // For now, return error if not available (in production, store separately)
    const birthDetails = {
      datetime: data.birthDetails?.datetime || data.birthDateTime,
      coordinates: data.birthDetails?.coordinates || data.coordinates,
      first_name: data.userName?.split(" ")[0] || "User",
      last_name: data.userName?.split(" ").slice(1).join(" ") || "",
      gender: kundli.gender || "male",
    };

    if (!birthDetails.datetime || !birthDetails.coordinates) {
      return NextResponse.json(
        { ok: false, error: "Birth details required for Prokerala PDF generation" },
        { status: 400 }
      );
    }

    // Prokerala PDF report endpoint
    try {
      const pdfResponse = await prokeralaRequest(
        "/report/personal-reading/instant",
        {
          input: birthDetails,
          options: options || {
            report: {
              brand_name: "AstroSetu",
              name: "Life Report",
              caption: "Generated by AstroSetu",
              la: "en",
            },
            template: {
              footer: "AstroSetu - Bridging humans with cosmic guidance",
              style: "vedic-astro-green",
            },
            modules: [
              {
                name: "personal-reading",
                options: {
                  chart_style: "south-indian",
                  include_dosha: true,
                  include_dasha: true,
                },
              },
            ],
          },
        },
        2,
        "POST" as const,
        true // Skip cache for PDF generation
      );

      // Prokerala returns PDF as base64 or blob
      if (pdfResponse.data?.pdf) {
        // Convert base64 to blob if needed
        const pdfBase64 = pdfResponse.data.pdf;
        const pdfBlob = Buffer.from(pdfBase64, 'base64');
        
        return new NextResponse(pdfBlob, {
          headers: {
            'Content-Type': 'application/pdf',
            'Content-Disposition': `attachment; filename="LifeReport_${data.userName || 'Report'}_${new Date().toISOString().split('T')[0]}.pdf"`,
          },
        });
      }

      return NextResponse.json(
        { ok: false, error: "PDF generation failed - invalid response from Prokerala" },
        { status: 500 }
      );
    } catch (prokeralaError: any) {
      console.error("[PDF] Prokerala PDF generation error:", prokeralaError);
      return NextResponse.json(
        { ok: false, error: `Prokerala PDF generation failed: ${prokeralaError?.message || "Unknown error"}` },
        { status: 500 }
      );
    }
  } catch (error) {
    return handleApiError(error);
  }
}

