/**
 * Mock Report Fixtures for Testing
 * Used when MOCK_MODE=true to avoid calling external APIs (AI + astrology providers)
 */

import type { ReportContent, ReportType } from "../types";

/**
 * Generate a mock report ID
 */
function generateMockReportId(): string {
  return `RPT-${Date.now()}-MOCK-${Math.random().toString(36).substring(7)}`;
}

/**
 * Create a basic mock report content structure
 */
function createBaseMockReport(reportType: ReportType, title: string): ReportContent {
  return {
    title,
    reportId: generateMockReportId(),
    generatedAt: new Date().toISOString(),
    sections: [
      {
        title: "Overview",
        content: "This is a mock report generated for testing purposes. In production, this would be generated by AI based on your birth chart analysis.",
        bullets: [
          "Mock data for development and testing",
          "Real reports use AI-powered analysis",
          "Enable real mode by setting MOCK_MODE=false",
        ],
      },
      {
        title: "Key Insights",
        content: "Key insights would appear here in a real report.",
      },
    ],
    summary: "This is a mock report summary. Real reports provide personalized insights based on astrological analysis.",
    keyInsights: [
      "Mock insight 1: This is test data",
      "Mock insight 2: Real reports are personalized",
      "Mock insight 3: Enable real mode for actual analysis",
    ],
  };
}

/**
 * Mock report fixtures for each report type
 */
export const MOCK_REPORTS: Record<ReportType, () => ReportContent> = {
  "life-summary": () => ({
    ...createBaseMockReport("life-summary", "Your Life Summary"),
    sections: [
      {
        title: "Executive Summary",
        content:
          "This is a mock Life Summary used for testing. In production, your summary will be generated from your birth chart and tailored to your unique patterns and preferences.",
      },
      {
        title: "Top Strengths",
        content: "A few strengths that tend to support your life direction (mock data):",
        bullets: [
          "Strong intuitive abilities (mock data)",
          "Natural leadership qualities (mock data)",
          "Creative problem-solving approach (mock data)",
          "Resilience under pressure (mock data)",
          "Ability to learn quickly from feedback (mock data)",
        ],
      },
      {
        title: "Key Challenges",
        content: "A few challenges to watch and work with (mock data):",
        bullets: [
          "Overthinking during transitions (mock data)",
          "Taking on too much responsibility (mock data)",
          "Difficulty resting when goals are unfinished (mock data)",
        ],
      },
      {
        title: "Relationships & Communication",
        content: "Your relationship style tends to improve with clarity and calm communication (mock data).",
        bullets: [
          "Best approach: say needs early and kindly (mock data)",
          "Watch-outs: silence when stressed (mock data)",
          "Support: boundaries + consistent routines (mock data)",
        ],
      },
      {
        title: "Career & Money Themes",
        content: "Career growth often follows focus and skill-building (mock data).",
        bullets: [
          "Strength: steady execution (mock data)",
          "Growth lever: deepen one core skill (mock data)",
          "Money habit: automate savings (mock data)",
        ],
      },
      {
        title: "Health & Energy Themes",
        content: "Energy is strongest when sleep and movement are consistent (mock data).",
        bullets: [
          "Helpful: morning light + walk (mock data)",
          "Helpful: hydration and regular meals (mock data)",
          "Watch-outs: long late nights (mock data)",
        ],
      },
      {
        title: "Growth & Spiritual Themes",
        content: "Growth tends to come from reflection plus small, repeatable actions (mock data).",
        bullets: [
          "Reflect: what drains vs restores you (mock data)",
          "Practice: weekly review (mock data)",
          "Balance: ambition with recovery (mock data)",
        ],
      },
      {
        title: "Next 30 Days: Quick Wins",
        content: "Three small actions that create momentum (mock data):",
        bullets: [
          "Pick one priority for the week and finish it (mock data)",
          "Send one message to strengthen a key relationship (mock data)",
          "Do 20 minutes of skill-building 3x/week (mock data)",
        ],
      },
    ],
    summary:
      "Mock summary: a structured Life Summary with enough sections to feel valuable. In production, this will be personalized to your birth chart.",
  }),

  "marriage-timing": () => ({
    ...createBaseMockReport("marriage-timing", "Marriage Timing Report"),
    timeWindows: [
      {
        title: "Favorable Period 1",
        startDate: "2025-06-01",
        endDate: "2025-08-31",
        description: "A favorable period for marriage-related decisions (mock data).",
        actions: ["Consider engagement", "Plan wedding ceremonies"],
        avoidActions: ["Major life changes unrelated to relationships"],
      },
    ],
    recommendations: [
      {
        category: "Timing",
        items: ["Focus on relationship development during favorable periods"],
        priority: "High",
      },
    ],
  }),

  "career-money": () => ({
    ...createBaseMockReport("career-money", "Career & Money Report"),
    timeWindows: [
      {
        title: "Career Growth Period",
        startDate: "2025-03-01",
        endDate: "2025-05-31",
        description: "A period favorable for career advancement (mock data).",
        actions: ["Explore new opportunities", "Invest in skill development"],
      },
    ],
    recommendations: [
      {
        category: "Career",
        items: ["Focus on professional development", "Network strategically"],
        priority: "High",
      },
      {
        category: "Finance",
        items: ["Plan investments carefully", "Save during favorable periods"],
        priority: "Medium",
      },
    ],
  }),

  "full-life": () => ({
    ...createBaseMockReport("full-life", "Full Life Report"),
    executiveSummary: "This mock full life report provides a comprehensive overview. Real reports analyze career, relationships, health, and finances in detail.",
    sections: [
      {
        title: "Career Analysis",
        content: "Your career path shows potential for growth and success (mock data).",
      },
      {
        title: "Relationship Insights",
        content: "Your relationship patterns and compatibility indicators (mock data).",
      },
      {
        title: "Health & Wellness",
        content: "Astrological insights into health and wellness (mock data).",
      },
    ],
  }),

  "year-analysis": () => ({
    ...createBaseMockReport("year-analysis", "Year Analysis Report"),
    yearTheme: "A year of growth and transformation (mock data)",
    quarterlyBreakdown: [
      {
        quarter: "Q1",
        focusTheme: "New beginnings and planning",
        careerMoneyTone: "Positive momentum",
        relationshipFocus: "Strengthening connections",
        energyLevel: "high",
      },
      {
        quarter: "Q2",
        focusTheme: "Building and expansion",
        careerMoneyTone: "Steady progress",
        relationshipFocus: "Deepening relationships",
        energyLevel: "moderate",
      },
      {
        quarter: "Q3",
        focusTheme: "Harvest and reflection",
        careerMoneyTone: "Consolidation",
        relationshipFocus: "Nurturing bonds",
        energyLevel: "moderate",
      },
      {
        quarter: "Q4",
        focusTheme: "Completion and preparation",
        careerMoneyTone: "Planning for next year",
        relationshipFocus: "Gratitude and connection",
        energyLevel: "high",
      },
    ],
    bestPeriods: [
      {
        months: ["March", "April", "May"],
        focus: "Career and financial growth",
        description: "Favorable period for professional advancement (mock data)",
      },
    ],
    cautionPeriods: [
      {
        months: ["September", "October"],
        focus: "Take care with major decisions",
        description: "Period requiring careful consideration (mock data)",
      },
    ],
    yearScorecard: {
      career: 4,
      relationships: 4,
      money: 3,
    },
    confidenceLevel: 8,
  }),

  "major-life-phase": () => ({
    ...createBaseMockReport("major-life-phase", "3-5 Year Strategic Life Phase Report"),
    phaseTheme: "A transformative phase of growth and change (mock data)",
    phaseYears: "2025-2029",
    phaseBreakdown: [
      {
        year: "Year 1 (2025)",
        theme: "Foundation building",
        focusAreas: ["Career establishment", "Relationship development"],
        majorInfluences: "Planetary alignments favor new beginnings",
      },
      {
        year: "Year 2-3 (2026-2027)",
        theme: "Expansion and growth",
        focusAreas: ["Professional advancement", "Financial stability"],
        majorInfluences: "Favorable periods for major life changes",
      },
    ],
    majorTransitions: [
      {
        type: "career",
        timeframe: "2025-2026",
        description: "Significant career transition opportunities (mock data)",
        preparation: ["Build skills", "Network strategically"],
      },
    ],
    longTermOpportunities: [
      {
        category: "Career",
        timeframe: "2025-2028",
        description: "Long-term career growth opportunities (mock data)",
        actionItems: ["Continuous learning", "Strategic planning"],
      },
    ],
  }),

  "decision-support": () => ({
    ...createBaseMockReport("decision-support", "Decision Support Report"),
    decisionContext: "This mock report helps evaluate decision options based on astrological timing (mock data).",
    decisionOptions: [
      {
        option: "Option A: Proceed immediately",
        astrologicalAlignment: "high",
        timeframe: "Next 3 months",
        considerations: ["Favorable planetary alignment", "Strong timing"],
      },
      {
        option: "Option B: Wait and plan",
        astrologicalAlignment: "medium",
        timeframe: "6-12 months",
        considerations: ["Better preparation time", "More favorable conditions later"],
      },
    ],
    recommendedTiming: "The next 3-6 months show favorable alignment for decision-making (mock data).",
    factorsToConsider: [
      "Planetary positions favor action",
      "Personal chart indicators suggest timing",
      "External factors to monitor",
    ],
  }),

  "daily-guidance": () => ({
    ...createBaseMockReport("daily-guidance", "Daily Guidance"),
    // Daily guidance has a simpler structure
    sections: [
      {
        title: "Today's Focus",
        content: "This is mock daily guidance. Real guidance is personalized for each day.",
      },
    ],
  }),
};

/**
 * Get mock report content for a given report type
 */
export function getMockReport(reportType: ReportType): ReportContent {
  const generator = MOCK_REPORTS[reportType];
  if (!generator) {
    throw new Error(`No mock report generator for type: ${reportType}`);
  }
  return generator();
}

/**
 * Simulate API delay (for realistic testing)
 */
export async function simulateApiDelay(minMs: number = 1500, maxMs: number = 3000): Promise<void> {
  const delay = minMs + Math.random() * (maxMs - minMs);
  await new Promise((resolve) => setTimeout(resolve, delay));
}

